name: Docker Image CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: build
      run:  docker build -t artur9022/flaskapp_production .
      

   

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: artur9022
          password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          push: true
          tags: artur9022/flaskapp_production:latest

    
